package com.complexparking.utils.preferences

const val IS_WIZARD_COMPLETED = "IS_WIZARD_COMPLETED"
const val USER_DATA = "USER_DATA"
const val IS_ADMIN_USER = "IS_ADMIN_USER"

const val SEED_DATA_LOADED = "SEED_DATA_LOADED"
const val DEFAULT_PRINTER = "DEFAULT_PRINTER"
const val ARE_PERMISSIONS_GRANTED = "ARE_PERMISSIONS_GRANTED"